# Generated by Django 4.1.9 on 2023-08-29 08:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fitness_tracker.users.abstract.models
import fitness_tracker.users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other"), ("N", "Prefer Not to Say")],
                        default="M",
                        help_text="Select the gender of the user.",
                        max_length=11,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Enter the date of birth of the user.",
                        validators=[fitness_tracker.users.validators.validate_date_of_birth],
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The calculated age of the user in years.",
                        null=True,
                        verbose_name="Age in years",
                    ),
                ),
                (
                    "contact_number",
                    fitness_tracker.users.abstract.models.MobileNumberField(
                        help_text="Enter the mobile number of the user.", verbose_name="Mobile Number of the User"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        help_text="Enter your height in centimeters.",
                        validators=[
                            django.core.validators.MinValueValidator(1, message="Height must be a positive value.")
                        ],
                        verbose_name="Height (cm)",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        help_text="Enter your weight in kilograms.",
                        validators=[
                            django.core.validators.MinValueValidator(1, message="Weight must be a positive value.")
                        ],
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "bmi",
                    models.FloatField(
                        blank=True,
                        help_text="Calculated Body Mass Index (BMI). Automatically populated.",
                        null=True,
                        verbose_name="Body Mass Index",
                    ),
                ),
                (
                    "joining_date",
                    models.DateField(
                        blank=True,
                        help_text="Enter the date when the user joined.",
                        null=True,
                        verbose_name="Joining Date",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("WL", "Weight Loss"),
                            ("GF", "General Fitness"),
                            ("SF", "Sports Fitness"),
                            ("WG", "Weight Gain"),
                            ("BR", "Body Recomposition"),
                        ],
                        default="GF",
                        help_text="Select the fitness goal of the user.",
                        max_length=2,
                        verbose_name="Fitness Goal",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Profile",
                    ),
                ),
            ],
        ),
    ]
