# Generated by Django 4.1.9 on 2023-08-29 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_fitnessprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitnessprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fitness_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fitness Profile",
            ),
        ),
    ]
